# Generated by Django 4.1.5 on 2023-02-05 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('discount_calculation', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=16)),
                ('release_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('last_use_date', models.DateTimeField()),
                ('purchases_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('orders', models.ManyToManyField(to='main_app.order')),
            ],
        ),
    ]
