# Generated by Django 4.1.5 on 2023-02-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_use_date',
            field=models.DateTimeField(null=''),
        ),
    ]
