# Generated by Django 4.1.5 on 2023-02-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_card_last_use_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='purchases_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
