# Generated by Django 4.1.5 on 2023-02-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_card_purchases_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='purchases_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
